// <auto-generated />
using System;
using InvoiceBackend.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250410140817_SeedReckonTokenData")]
    partial class SeedReckonTokenData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceBackend.Domain.Entities.ReckonToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("ReckonTokens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessToken = "bfdf433c15482b40aa1940d865a999ec",
                            CreatedAt = new DateTime(2025, 4, 10, 13, 47, 37, 277, DateTimeKind.Unspecified).AddTicks(1703),
                            ExpiryTime = new DateTime(2025, 4, 10, 16, 47, 37, 276, DateTimeKind.Unspecified).AddTicks(6302),
                            RefreshToken = "32f262f7c1cc60767bc9da0f15c2a3e6",
                            SessionId = "888",
                            TokenType = "Bearer",
                            UpdatedAt = new DateTime(2025, 4, 10, 13, 47, 37, 277, DateTimeKind.Unspecified).AddTicks(1951)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
